// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdjcdbzeodgeljthoiyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkamNkYnplb2RnZWxqdGhvaXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTI1MjEsImV4cCI6MjA2OTA4ODUyMX0.bP9OGhjMTxwbVUZwyCFlTXkSZZQb_VsVeO3i2JRGpWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});